#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

if [ ! -f "$OPENSHIFT_DATA_DIR"secrets.json ]; then
        echo "Generating $OPENSHIFT_DATA_DIR/secrets.json"
        python "$OPENSHIFT_REPO_DIR"libs/secrets.py > "$OPENSHIFT_DATA_DIR"secrets.json
fi

# GETTING-STARTED: change 'main' to your project name:
echo "Executing 'python $OPENSHIFT_REPO_DIRwsgi/manage.py migrate --noinput --settings=main.settings.production'"
# GETTING-STARTED: change 'main' to your project name:
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py migrate --noinput --settings=main.settings.production

# GETTING-STARTED: change 'main' to your project name:
echo "Executing 'python $OPENSHIFT_REPO_DIRwsgi/main/manage.py collectstatic --noinput --settings=main.settings.production'"
# GETTING-STARTED: change 'main' to your project name:
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py collectstatic --noinput --settings=main.settings.production

psql -d fsis2 -f "$OPENSHIFT_REPO_DIR"wsgi/fsis2/sql/cwt_procedures.sql
