((nil . ((virtualenv-workon . "fsis2")
         (virtualenv-default-directory . "c:/Users/cottrillad/documents/1work/Python/djcode/fsis2/")
         ;;(pytest-global-name . "C:/Users/cottrillad/documents/1work/.virtualenv/fsis2/Scripts/py.test")
         (pytest-global-name . "py.test")
         (python-shell-interpreter . "C:/Users/cottrillad/documents/1work/.virtualenv/fsis2/Scripts/python.exe")
         ;;(python-shell-interpreter-args . "-i C:/Users/cottrillad/documents/1work/.virtualenv/ipython/Scripts/ipython-script.py")
         ;;(python-shell-interpreter-args . "c:/Users/cottrillad/documents/1work/Python/djcode/fsis2/manage.py shell")
         (python-shell-extra-pythonpaths "c:/Users/cottrillad/documents/1work/Python/djcode/fsis2/")
  ))
)
