* FSIS-II - What FSIS could have been

FSIS-II is a django application that was written to display and
summarize fish stocking data for the Ontario waters of Lake Huron.  A
provincial stocking application exists, but it is poorly designed,
limited to data entry, and does not include data prior to 2001.
FSIS-II is provides an interactive web-based application that makes
viewing, summarizing and exploring fish stocking data easy and
intuitive.

Questions like this are now easy to answer and visualize:
- Where were rainbow trout stocked in 2002?
- Where is 'Horton's Point'?
- How many fish were tagged with cwt '63-56-14' and how many have been
  recovered?  Where were they stocked and where were they recovered?
- When did Ontario stop stocking splake and move to pure strain lake
  trout?
- How many fish and of what species have been stocked here?

The basic data model of fish stocking data includes fish lots,
stocking events, tagging events and tags applied.  For the purposes
of this application, a lot of fish is defined as a group of fish of
the same year class, species, and strain, raised by one proponent.
A stocking event can be thought of a single 'pipe-in-the-water',
although tags often require a duplicate event to capture stocking
information associated with both tagged and untagged fish that are
often stocked together.

FSIS-II includes several list views for presenting lots, events, cwts,
events by proponent, and annual summaries by species and/or strain.
Where appropriate, point data (lat-long) is displayed on an
interactive map.

** Stocking events by location

A form with an interactive map widget is also provided that can be
used to find all of the stocking events of one or more species in an
arbitrary polygon drawn by the user.

** Coded Wire Tags

All coded wire tags deployed into the waters of Lake Huron are also
presented in a list view.  A search box is provided with the list to
quickly retrieve cwts matching the provided pattern.  The details page
of each cwt include basic information about the tag included where and
when it was deployed, by which agency and in which species and strain,
as well as an age-at-capture matrix.  The stocking location and any
associated recoveries are displayed on an interactive map. The cwt
detail page also lists information about any known recoveries of that
tag number in any of the associated field programs run by the UGLMU,
and includes attributes like size and age at capture, date of
recovery, field program type, and key fields needed to identify the
specific record in the associated database.  Finally, the cwt detail
page displays a warning if the cwt appears to have been compromised in
some way (i.e. - stocked in more than one location, year class, or
strain).

*** CWTS stocked and recovered by Management Unit

Views have been created to display all of the stocking and subsequent
recovery locations for cwts in pre-defined management units.  Two
views are provided for each management unit - one for all of the
stocking events that occurred within the management area (to address
the question "Where did the fish stocked here end up?"), and one
illustrating the stocking locations of all recoveries in a management
area ('Where did fish caught in this management area come from?').
Currently, the management units are limited to LTRZs and QMAs, but any
management unit with an associated shapefile could be added if
desired.


** To Dos
- improve test coverage, fsis2 has relatively little test coverage
  currently.  This needs to be improved.
- find cwts by stocking area (filter by strain)
- find cwts by recovery area (filter by strain)
- find closest stocking sites given a point (either manually entered or
  based on mouse click)
- add map of pre- and post- FSIS stocking locations
- add convex hull to cwt recoveries map, (and to cwt stocking if cwt
  has been stocked in more than one location)
