# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-22 16:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fsis2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CWT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocked', models.BooleanField(default=True)),
                ('cwt', models.CharField(db_index=True, max_length=6)),
                ('seq_start', models.IntegerField(default=0)),
                ('seq_end', models.IntegerField(default=1)),
                ('tag_cnt', models.IntegerField(blank=True, null=True)),
                ('tag_type', models.IntegerField(choices=[(6, 'Coded Wire'), (17, 'Sequential CWT')], default=6)),
                ('cwt_mfr', models.CharField(choices=[('MM', 'Micro Mark'), ('NMT', 'Northwest Marine Technologies')], max_length=10)),
                ('cwt_reused', models.BooleanField(default=False)),
                ('strain', models.CharField(blank=True, choices=[('BS', 'Big Sound'), ('GL', 'Green Lake'), ('IB', 'Iroquois Bay'), ('JL', 'Jenny Lake'), ('LL', 'Lewis Lake'), ('LM', 'Lake Manitou'), ('LO', 'Lake Ontario'), ('MA', 'Marquette'), ('MASE', 'Marquette cross'), ('MP', 'Michipicoten Island'), ('SA', 'Apositle Island'), ('SI', 'Superior Isle Royal'), ('SN', 'Seneca Lake'), ('STI', 'Superior Traverse Island'), ('WI', 'Wisconsin'), ('MB', 'Mishubishu'), ('ST', 'Slate Island'), ('UNKN', 'Unknown')], max_length=10, null=True)),
                ('development_stage', models.IntegerField(blank=True, choices=[(99, 'Unknown'), (10, 'Egg (unknown stage)'), (12, 'Eyed Eggs'), (31, 'Fry (1-2 months)'), (32, 'Fingerling (3-9 months)'), (50, 'Juvenile / Adult (unknown age)'), (51, 'Yearling (10-19 months)'), (52, 'Sub-adult (>= 20 months, but immature)'), (53, 'Adult (mature)'), (81, 'Sac Fry (0-1 month)')], default=99, null=True)),
                ('year_class', models.IntegerField(blank=True, null=True)),
                ('stock_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('plant_site', models.CharField(blank=True, max_length=80, null=True)),
                ('release_basin', models.CharField(blank=True, choices=[('HU', 'Lake Huron'), ('MI', 'Lake Michigan'), ('SU', 'Lake Superior'), ('ER', 'Lake Superior'), ('MIHU', 'Lakes Huron and Michigan'), ('MIHUSU', 'Lakes Huron, Michigan and Superior'), ('UNKN', 'Unknown')], max_length=6, null=True)),
                ('us_grid_no', models.CharField(blank=True, max_length=4, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Represented as (longitude, latitude)', null=True, srid=4326)),
                ('ltrz', models.IntegerField(blank=True, choices=[(1, 'Western North Channel'), (2, 'Darch Islands'), (3, 'Fraser Bay'), (4, 'Grand Bank/Dawson Rock'), (5, 'Iroquois Bay'), (6, 'Parry Sound'), (7, 'Limestone Islands'), (8, 'Watcher Islands'), (9, 'Nottawasaga Bay'), (10, 'Owen Sound/Colpoys Bay'), (11, 'Point Clark'), (12, 'Western Bruce Penninsula'), (13, 'Bruce Archipelago'), (14, 'SW Manitoulin Island'), (15, 'South Bay'), (16, 'Six Fathom Bank'), (17, 'North Lake Huron Humps')], null=True)),
                ('hatchery', models.CharField(blank=True, max_length=80, null=True)),
                ('agency', models.CharField(choices=[('OMNR', 'Ontario Ministry of Natural Resources'), ('MIDNR', 'Michigan Department of Natural Resources'), ('USFWS', 'U.S. Fish and Wildlife Service'), ('CORA', 'CORA'), ('ILDNR', 'Illinois Department of Natural Resources'), ('INDNR', 'Indiana Department of Natural Resources'), ('WIDNR', 'Wisconsin Department of Natural Resources')], max_length=5)),
                ('comments', models.TextField(blank=True, null=True)),
                ('clipa', models.IntegerField(blank=True, choices=[(0, 'No Clip'), (1, 'Right Pectoral'), (2, 'Left Pectoral'), (3, 'Right Pelvic'), (4, 'Left Pelvic'), (14, 'Right Pectoral and Left Pelvic'), (23, 'Left Pectoral and Right Pelvic'), (5, 'Adipose')], default=5, null=True)),
                ('popup_text', models.CharField(max_length=5000)),
                ('spc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fsis2.Species')),
            ],
        ),
        migrations.CreateModel(
            name='CWT_recovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cwt', models.CharField(db_index=True, max_length=6)),
                ('sequence_number', models.IntegerField(default=0)),
                ('recovery_source', models.CharField(choices=[('AOFRC', 'AOFRC'), ('CF', 'Catch Sampling'), ('CWT', 'CWT Cooperative'), ('IA_Nearshore', 'Nearshore Index'), ('IA_Offshore', 'Offshore Index'), ('NAWASH', 'Nawash'), ('SportCreel', 'Creels'), ('SportFish', 'Sportfish')], max_length=20)),
                ('recovery_year', models.IntegerField(db_index=True)),
                ('recovery_date', models.DateField(blank=True, null=True)),
                ('recovery_grid', models.CharField(max_length=4)),
                ('composite_key', models.CharField(max_length=50)),
                ('flen', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326)),
                ('popup_text', models.CharField(max_length=2500)),
                ('spc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsis2.Species')),
            ],
        ),
    ]
