/* Access SQL export data follows. Auto-generated. */

/* Tables */
DROP TABLE [__README] /**WEAK**/;
CREATE TABLE [__README] (
[DATE] TEXT,
[COMMENT] TEXT,
[INIT] TEXT(50),
[DOC_LINK] TEXT
);

DROP TABLE [FS_CWTs_Applied] /**WEAK**/;
CREATE TABLE [FS_CWTs_Applied] (
[EVENT] REAL,
[TAG_ID] REAL,
[CWT] REAL
);
CREATE INDEX [FS_CWTs_AppliedEVENT] ON [FS_CWTs_Applied] (EVENT ASC);

DROP TABLE [FS_Events] /**WEAK**/;
CREATE TABLE [FS_Events] (
[YEAR] TEXT(255),
[PRJ_CD] TEXT(12),
[LOT] TEXT(255),
[Event] INTEGER,
[LOTSAM] TEXT(5),
[Event_Date] TEXT(255),
[SPC] TEXT(3),
[CLIPA] TEXT(5),
[FISH_AGE] REAL,
[STKCNT] INTEGER,
[DEV_CODE] TEXT(2),
[DEV_DESC] TEXT(255),
[FISH_WT] TEXT(7),
[TRANSIT] TEXT(255),
[METHOD] TEXT(255),
[STKWBY] TEXT(7),
[STKWBY_LID] TEXT(255),
[SITE_ID] INTEGER,
[SITE_NAME] TEXT(255),
[UTM] TEXT(255),
[GRID] TEXT(255),
[DD_LAT] REAL,
[DD_LON] REAL,
[BASIN] TEXT(255),
[DESWBY_LID] TEXT(255),
[DESWBY] TEXT(255),
[RECORD_BIOMASS_CALC] TEXT(255),
[REARTEM] TEXT(2),
[SITEM] TEXT(2),
[LOAD_CNT] TEXT(255),
[TRANSIT_MORTALITY_COUNT] TEXT(255),
[STKPUR] TEXT(2),
[STK_PUR_DESC] TEXT(255)
);
CREATE INDEX [FS_EventsEVENT] ON [FS_Events] (Event ASC);
CREATE INDEX [FS_EventsPRJ_CD] ON [FS_Events] (PRJ_CD ASC);


DROP TABLE [FS_Lots] /**WEAK**/;
CREATE TABLE [FS_Lots] (
[YEAR] TEXT(255),
[PRJ_CD] TEXT(12),
[LOT] TEXT(255),
[SPC] TEXT(3),
[STO] TEXT(5),
[SPAWN_YEAR] REAL,
[REARLOC] TEXT(7),
[REARLOC_NM] TEXT(25),
[PROPONENT_NAME] TEXT(20),
[PROPONENT_TYPE] TEXT(255)
);
CREATE INDEX [FS_LotsPRJ_CD] ON [FS_Lots] (PRJ_CD ASC);

DROP TABLE [FS_Sequential_Tags] /**WEAK**/;
CREATE TABLE [FS_Sequential_Tags] (
[EVENT] REAL,
[TAG_Group] TEXT(255),
[TAG_ID] REAL,
[TAG_SERIES] INTEGER,
[CWT] INTEGER,
[SERIES_START] REAL,
[SERIES_END] REAL,
[COMMENT] TEXT(50)
);

DROP TABLE [FS_TagAttributes] /**WEAK**/;
CREATE TABLE [FS_TagAttributes] (
[EVENT] INTEGER,
[TAG_ID] INTEGER,
[TAG_TYPE_CODE] INTEGER,
[TAG_TYPE_DESCRIPTION] TEXT(255),
[TAG_POSITION] TEXT(255),
[TAG_ORIGIN_CODE] TEXT(255),
[TAG_ORIGIN_DESCRIPTION] TEXT(255),
[TAG_COLOUR_CODE] TEXT(255),
[TAG_COLOUR_DESCRIPTION] TEXT(255),
[RETENTION_RATE_PCT] TEXT(5),
[RETENTION_RATE_SAMPLE_SIZE] TEXT(5),
[RETENTION_RATE_POP_SIZE] TEXT(7),
[COMMENTS] TEXT(255)
);
CREATE INDEX [FS_TagAttributesEvent] ON [FS_TagAttributes] (EVENT ASC);

DROP TABLE [TL_Proponents] /**WEAK**/;
CREATE TABLE [TL_Proponents] (
[ID] INTEGER,
[Proponent_Name] TEXT(255),
[Abbreviation] TEXT(10)
);

DROP TABLE [TL_Strains] /**WEAK**/;
CREATE TABLE [TL_Strains] (
[SPC] TEXT(3),
[STO] TEXT(5),
[StrainCode] TEXT(255),
[StrainName] TEXT(255) --, [COMMENT] TEXT(255)
);

DROP TABLE [YearlingEquivalents] /**WEAK**/;
CREATE TABLE [YearlingEquivalents] (
[LifeStage] TEXT(50),
[Factor] REAL DEFAULT 0,
[DEV_CODE] TEXT(2)
);
CREATE INDEX [DevCode] ON [YearlingEquivalents] (DEV_CODE ASC);


DROP TABLE [SPC] /**WEAK**/;
CREATE TABLE [SPC] (
[SPC] TEXT(3),
[SPC_LAB] TEXT(5),
[SPC_NM] TEXT(25),
[SPC_NMCO] TEXT(30),
[SPC_NMSC] TEXT(50),
[SPC_NMFAM] TEXT(30),
[COMMENT] TEXT,
[Quota_Flag] INTEGER
);


DROP TABLE [TL_ActualStockingSites] /**WEAK**/;
CREATE TABLE [TL_ActualStockingSites] (
[Event] INTEGER,
[DD_LAT] REAL,
[DD_LON] REAL);
